apiVersion: v1
kind: Secret
metadata: 
  namespace: three-tier
  name: mongo-sec
type: Opaque
data:  
  password: cGFzc3dvcmQxMjM=   #Three-Tier-Project using base64
  username: UmFqYXRfc2F4ZW5hCg== #Rajat_saxena using base64